version: '3.8'
services:
  kindle:
    build: 
        context: . 
        dockerfile: Dockerfile
    container_name: kindle
    ports:
    - "8080:80"
    environment:
        PHP_INI_UPLOAD_MAX_FILESIZE: 25M
        PHP_INI_POST_MAX_SIZE: 25M
    volumes:
    - ./app:/var/www/html