version: '3.8'
services:
  kindle:
    build: 
        context: . 
        dockerfile: Dockerfile
    container_name: kindle
    ports:
    - "8080:80"
    environment:
        PHP_EXTENSION_MYSQLI : 0
        PDO : 0
        PDO_MYSQL : 0
    volumes:
    - ./app:/var/www/html